Area:
  World: world
  '1':
    X: 0
    Y: 0
    Z: 0
  '2':
    X: 0
    Y: 0
    Z: 0
Kit: |
  rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
  dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
  bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
  Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
  AAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr
  dAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEA
  fgALdAADQk9XcHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXQABmFtb3VudHVx
  AH4ABgAAAANxAH4AC3QAC0NPT0tFRF9CRUVGc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgC
  AAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAApzcQB+AABzcQB+
  AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAVdXEAfgAGAAAAA3EAfgALdAAFQVJST1dzcQB+ABgA
  AAAgcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
