#--------------------------------------------------#
#                                                  #
#            PlayTimeRank Plugin                   #
#            Coded by DevOFVictory                 #
#                                                  #
#--------------------------------------------------#

Prefix: "[&4PlayTime&r] "